- name: Base setup on all hosts
  hosts: all
  become: true
  roles:
    - common-setup

- name: Configure dbservers (staging + production)
  hosts: db
  become: true
  roles:
    - mysql-setup
    - setup-schema

- name: Configure web servers (staging + production)
  hosts: web
  become: true
  roles:
    - nginx-setup
    - php-fpm-setup
    - deploy-app