- name: Install prerequisites for PHP repository
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
    state: present
    update_cache: yes

- name: Add Sury GPG key
  ansible.builtin.get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/sury.gpg
    mode: '0644'

- name: Add Sury PHP repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/sury-php.list
    create: yes
    line: "deb https://packages.sury.org/php/ {{ ansible_facts.distribution_release }} main" # specify the correct distribution release

- name: Update apt cache after adding PHP repo
  ansible.builtin.apt:
    update_cache: yes